# Generated by Django 5.1.4 on 2026-04-24 06:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import hospital.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('RECEPTIONIST', 'Receptionist'), ('ADMIN', 'Admin')], default='PATIENT', max_length=20)),
                ('mobile_no', models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number starting with 6-9.', regex='^[6-9]\\d{9}$')])),
                ('alt_mobile_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number starting with 6-9.', regex='^[6-9]\\d{9}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Staff must be approved by Admin before they can log in.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('relation', models.CharField(choices=[('SELF', 'Self'), ('SPOUSE', 'Spouse'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dependent',
                'verbose_name_plural': 'Dependents',
                'unique_together': {('patient', 'name', 'dob')},
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200)),
                ('department', models.CharField(db_index=True, max_length=200)),
                ('available_days', models.CharField(default='MON,TUE,WED,THU,FRI', help_text='Comma-separated: MON,TUE,...', max_length=50)),
                ('consultation_start', models.TimeField(default='09:00')),
                ('consultation_end', models.TimeField(default='17:00')),
                ('max_patients_per_day', models.PositiveIntegerField(default=30)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('token_number', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='WAITING', max_length=20)),
                ('chief_complaint', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Doctor/Nurse notes')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('dependent', models.ForeignKey(blank=True, help_text='Leave blank if appointment is for the patient themselves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospital.dependent')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.doctorprofile')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['date', 'token_number'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('urgency', models.CharField(choices=[('RED', '🔴 RED — Emergency'), ('YELLOW', '🟡 YELLOW — Warning'), ('GREEN', '🟢 GREEN — Advice / Suggestion')], default='GREEN', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_resolved', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(help_text='e.g., X-Ray, Blood Report, MRI', max_length=200)),
                ('report_file', models.FileField(help_text='Max file size: 5 MB', upload_to='medical_reports/%Y/%m/', validators=[hospital.models.validate_file_size])),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='hospital.appointment')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(db_index=True, max_length=200)),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('mfg_date', models.DateField(verbose_name='Manufacturing Date')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='Expiry Date')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('TAB', 'Tablet'), ('CAP', 'Capsule'), ('SYR', 'Syrup (ml)'), ('INJ', 'Injection'), ('DROP', 'Drops'), ('OIN', 'Ointment (g)'), ('POW', 'Powder (g)'), ('OTHER', 'Other')], default='TAB', max_length=10)),
                ('shelf_location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['medicine_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='e.g., 1 tablet twice daily after food', max_length=200)),
                ('duration_days', models.PositiveIntegerField(default=5)),
                ('quantity_prescribed', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('stock_status', models.CharField(choices=[('FREE_IN_STOCK', '✅ FREE — In Stock'), ('OUT_OF_STOCK', '❌ Out of Stock — Purchase Outside'), ('EXPIRED', '⚠️ Expired')], editable=False, max_length=20)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.appointment')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='hospital.medicine')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='StockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Added to Stock'), ('REMOVE', 'Removed from Stock'), ('DISPENSE', 'Dispensed via Prescription'), ('EXPIRE', 'Marked Expired')], max_length=20)),
                ('quantity_changed', models.IntegerField(help_text='Positive = added, Negative = removed')),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.TextField(help_text='Why was this change made?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='hospital.medicine')),
                ('pharmacist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, help_text='Linked prescription if this was a dispense action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.prescription')),
            ],
            options={
                'verbose_name': 'Stock Audit Log',
                'verbose_name_plural': 'Stock Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'doctor', 'status'], name='hospital_ap_date_ce6175_idx'),
        ),
    ]
