# Generated by Django 5.1.4 on 2026-04-24 06:45

import django.db.models.deletion
import hospital.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stockauditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='Max 5MB', null=True, upload_to='feedback/', validators=[hospital.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospital.dependent'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mfg_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('TAB', 'Tablet'), ('CAP', 'Capsule'), ('SYR', 'Syrup'), ('INJ', 'Injection'), ('DROP', 'Drops'), ('OIN', 'Ointment'), ('POW', 'Powder'), ('OTHER', 'Other')], default='TAB', max_length=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockauditlog',
            name='action',
            field=models.CharField(choices=[('ADD', 'Added to Stock'), ('REMOVE', 'Removed from Stock'), ('DISPENSE', 'Dispensed via Prescription')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockauditlog',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.medicine'),
        ),
        migrations.AlterField(
            model_name='stockauditlog',
            name='pharmacist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockauditlog',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.prescription'),
        ),
        migrations.AlterField(
            model_name='stockauditlog',
            name='quantity_changed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockauditlog',
            name='reason',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Max 5MB', upload_to='ehr/', validators=[hospital.models.validate_file_size])),
                ('category', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('PAST_HISTORY', 'Archived Past History')], default='LAB_REPORT', max_length=20)),
                ('record_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='hospital.appointment')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-record_date', '-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='MedicalReport',
        ),
    ]
