# Generated by Django 5.1.4 on 2026-04-28 10:38

import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_feedback_options_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(validators=[hospital.models.validate_150_words]),
        ),
    ]
