# Generated by Django 5.1.4 on 2026-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_feedback_status_alter_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
