# Generated by Django 5.1.4 on 2026-04-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_feedback_admin_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='linked_member',
            field=models.ForeignKey(blank=True, help_text='Leave blank if the record is for the account holder (Self).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='hospital.dependent'),
        ),
    ]
