# Generated by Django 5.1.4 on 2026-04-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_customuser_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. MBBS, MD, MS', max_length=200, null=True),
        ),
    ]
