# Generated by Django 5.1.4 on 2026-04-29 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_doctorprofile_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_advice',
            field=models.TextField(blank=True, help_text='Final advice for the patient.'),
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='hospital.appointment')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=5)),
                ('bp_systolic', models.PositiveIntegerField(help_text='mmHg')),
                ('bp_diastolic', models.PositiveIntegerField(help_text='mmHg')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='°F', max_digits=4)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='hospital.appointment')),
            ],
        ),
    ]
