# Generated by Django 5.1.4 on 2026-04-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_appointment_doctor_advice_laborder_patientvitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='pulse',
            field=models.PositiveIntegerField(blank=True, help_text='bpm', null=True),
        ),
    ]
